﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using ApiSchema.v1;
using Refit;
using System.Text;
using System.Threading.Tasks;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace ApiClient.Api.v1
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedCompaniesApi : CompaniesApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedCompaniesApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<Company> GetCompany(int companyId)
        {
            var arguments = new object[] { companyId };
            return (Task<Company>) methodImpls["GetCompany"](Client, arguments);
        }

        public virtual Task<List<Company>> GetAllCompanies()
        {
            var arguments = new object[] {  };
            return (Task<List<Company>>) methodImpls["GetAllCompanies"](Client, arguments);
        }

    }
}

namespace ApiClient.Api.v1
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedIMockApi : IMockApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedIMockApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual Task<Product> GetProduct(int productId)
        {
            var arguments = new object[] { productId };
            return (Task<Product>) methodImpls["GetProduct"](Client, arguments);
        }

        public virtual Task<List<Product>> GetAllProducts()
        {
            var arguments = new object[] {  };
            return (Task<List<Product>>) methodImpls["GetAllProducts"](Client, arguments);
        }

    }
}


